// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: counter.sql

package database

import (
	"context"
)

const getCounter = `-- name: GetCounter :one
select counter from counter where id = 1
`

func (q *Queries) GetCounter(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCounter)
	var counter int64
	err := row.Scan(&counter)
	return counter, err
}

const updateCounter = `-- name: UpdateCounter :one
update counter set counter = ? where id = 1 returning counter
`

func (q *Queries) UpdateCounter(ctx context.Context, counter int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateCounter, counter)
	err := row.Scan(&counter)
	return counter, err
}
